### ISSUE TITLE
Badges - Edit - Error

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#11]
![badge edit error](https://cloud.githubusercontent.com/assets/9812202/7403279/4d0e3d7e-ee91-11e4-9bac-893226630966.JPG)

**Comment by conarwelsh** [comment]
nothing I can do about this, this was what I was referencing in the email.  Status updates, mentions, etc in status updates were formatted differently than they are now.  Visually it still looks good, but when you pull it into an editor it will turn into this.  You can manually delete the html and format per the new way but thats it.
