### ISSUE TITLE
Profile - Email a TM

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#13]
This is not working...appears as though the code is not accurate?

![email to tm](https://cloud.githubusercontent.com/assets/9812202/7403306/9db0fa6e-ee91-11e4-8f34-648a550e8be1.JPG)

Should be something more like this?

![mailto code](https://cloud.githubusercontent.com/assets/9812202/7403311/a7f7bea4-ee91-11e4-9ba6-c1f6fb57020d.JPG)

**Comment by conarwelsh** [comment]
look 2 lines above your circle

**Comment by deldewindt** [comment]
I can't get it to work on my computer?  Can you on yours?
