### ISSUE TITLE
Help Desk - Order of Tickets

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#15]
![final_help desk order](https://cloud.githubusercontent.com/assets/9812202/7403332/d9dd8872-ee91-11e4-9d7e-7059143db905.JPG)

**Comment by deldewindt** [comment]
Known issue for weeks.  Commented on this several times.

**Comment by conarwelsh** [comment]
and i always recommented back there is nothing I can do about it.  It is the nature of how they are created.
