### ISSUE TITLE
Search - Teammate Card vs. Random Info

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#22]
![search - teammate results should be their tm card](https://cloud.githubusercontent.com/assets/9812202/7403414/bfe5d810-ee92-11e4-9f0a-cf4f0898ef00.JPG)

Should be:

![image](https://cloud.githubusercontent.com/assets/9812202/7403420/d4be6b4e-ee92-11e4-9637-1415b961d7b8.png)

**Comment by conarwelsh** [comment]
we have been through this so many times its scary.  I do not have all of that info available in the list
