### ISSUE TITLE
Teammates & Teams - Recently Added?

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#29]
What timeline is this Recently Added set to?  Currently it's everybody, which sort of defeats the purpose.

![what timeline is this set to](https://cloud.githubusercontent.com/assets/9812202/7403551/fda8f17c-ee93-11e4-82b0-2250ba007409.JPG)

**Comment by conarwelsh** [comment]
it just sorts the created at timestamp in descending order.  It was a request a while back.

**Comment by deldewindt** [comment]
ok
