### ISSUE TITLE
Admin - Teammates - Sorting & Pagination

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#30]
If you sort by anything other than Last Name (i.e. First Name in this example) and then click on the pagination to continue sorting it reverts back to the default sorting of Alphabetical by Last Name.

![image](https://cloud.githubusercontent.com/assets/9812202/7419042/a5ac3fbe-ef2f-11e4-994d-ad18314a583e.png)

See, when I click on Page 2 of the Pagination it reverts back to Last Name sorting by alphabetical order.
![image](https://cloud.githubusercontent.com/assets/9812202/7419053/bea0e8e4-ef2f-11e4-8007-7fad402503b4.png)

**Comment by conarwelsh** [comment]
I cannot change that right now, it could potentially break a lot of parts of the application.
