### ISSUE TITLE
Admin - Creating a New Teammate

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#369]
For an Admin to create a new TM there are some things that aren't making sense.  I.e. I want the Admin to create a username & password for a TM then have an email or something sent to them stating to login and complete their profile.  

Currently, the Admin is being required to fill out all "required fields" like Hometown and Favorite Core Value.  This doesn't make sense.

![image](https://cloud.githubusercontent.com/assets/9812202/7267853/bd6e8f06-e87e-11e4-8da3-131e30810bba.png)

**Comment by conarwelsh** [comment]
I know, I tried to tell you this before.  You made a ticket specifically delcaring all of these fields as required.  I had it so only username and password are required.

**Comment by deldewindt** [comment]
When creating a new Teammate for the first time (each time we create a new
TM) can it simply be a "shadow" TM where we create a username, password &
email  ONLY.  An email is then sent to that TM for them to setup all other
required fields?


*Del de Windt*  |  Chief Executive Officer



4100 E. Mississippi Ave, Floor 15  |  Denver, CO 80246
o. 303.407.4500  |  f. 303.374.2942
Del@CardinalGroup.com  |  www.CardinalGroup.com

**Comment by conarwelsh** [comment]
No emails send out of the system, so no.  But I can make it so those fields are not required anymore like it used to be
