### ISSUE TITLE
Profile - Favorite Core Value - Number issue

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#371]
This is the problem with the numbering system...Core Value #1 is showing "0." 

![image](https://cloud.githubusercontent.com/assets/9812202/7267938/ec21df5a-e87f-11e4-95d5-4b80cf037522.png)

**Comment by conarwelsh** [comment]
thats the number you assigned to it in the admin
i just changed the values on this http://45.56.89.62/admin/settings
