### ISSUE TITLE
Search - Teammate Default Profile Picture

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#377]
This needs to be the default image:

![image](https://cloud.githubusercontent.com/assets/9812202/7268180/b11f2c38-e883-11e4-898e-488387c6b293.png)

**Comment by conarwelsh** [comment]
@deldewindt we do not have all the regular default images available here, we merely know whether or not there is an image.  I can hide the image altogether in the case that one is not set.  I have set it to this for now, we can change if not
