### ISSUE TITLE
Teams - Card Design

### ISSUE THREAD

**Issue by deldewindt** [CardinalGroup/dashboard#378]
1. Need to add description
2. Need to add "Last Activity" time stamp

![image](https://cloud.githubusercontent.com/assets/9812202/7268254/8f3d2bc8-e884-11e4-96d8-7cc5ca993915.png)

Current view:
![image](https://cloud.githubusercontent.com/assets/9812202/7268260/aeab37ca-e884-11e4-970d-4f315a73939a.png)

**Comment by conarwelsh** [comment]
last activity does not exist
